apiVersion: v1
kind: Secret
metadata:
  name: fpl-secrets
  namespace: fpl-system
type: Opaque
stringData:
  POSTGRES_USER: mluser
  POSTGRES_PASSWORD: mlpass
  RAW_DB_NAME: rawdb
  FEATURE_DB_NAME: featuredb
