apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predict-api
  namespace: fpl-system
spec:
  ingressClassName: traefik
  rules:
    - host: fpl.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: predict-api
                port:
                  number: 8000
